general {
    gaps_in = 5
    gaps_out = 10

    border_size = 2

    col.active_border = rgba(cba6f7ff)
    col.inactive_border = rgba(585b70aa)

    resize_on_border = false

    allow_tearing = true

    layout = dwindle
}
