# =========================================================
# WINDOW RULES
# =========================================================

# ---------- CORE FIXES ----------

windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags

    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# ---------- DIALOGS ----------

windowrule {
    name = dialogs-float

    match:title = ^(Open|Save|Confirm|Choose|File Operation Progress).*

    float = true
    center = true
}

windowrule {
    name = modal-dialogs

    match:modal = true

    float = true
    center = true
}

# ---------- FLOATING UTILITIES ----------

windowrule {
    name = float-pavucontrol

    match:class = ^(pavucontrol)$

    float = true
    center = true
}

windowrule {
    name = float-networkmanager

    match:class = ^(nm-connection-editor)$

    float = true
    center = true
}

windowrule {
    name = float-blueman

    match:class = ^(blueman-manager)$

    float = true
    center = true
}

# ---------- MULTIMEDIA ----------

windowrule {
    name = idle-inhibit-media

    match:class = ^(mpv|vlc|celluloid)$

    idle_inhibit = fullscreen
}

windowrule {
    name = idle-inhibit-browser

    match:class = ^(firefox|LibreWolf|brave-browser|chromium)$

    idle_inhibit = fullscreen
}

# ---------- PICTURE IN PICTURE ----------

windowrule {
    name = picture-in-picture

    match:title = ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture).*

    float = true
    pin = true
    keep_aspect_ratio = true
    size = 500 300
}

# ---------- JETBRAINS FIX ----------

windowrule {
    name = jetbrains-fix

    match:class = ^(.jetbrains.)$
    match:title = ^(win[0-9]+)$

    no_initial_focus = true
}

# ---------- LAYER RULES ----------

layerrule = blur true,match:namespace rofi
layerrule = ignore_alpha 0,match:namespace rofi

layerrule = blur true,match:namespace notifications
layerrule = ignore_alpha 0,match:namespace notifications



# ---------- STEAM ----------

windowrule {
    name = steam-friends

    match:title = ^(Friends List)$

    float = true
    center = true
}

windowrule {
    name = steam-settings

    match:title = ^(Steam Settings)$

    float = true
    center = true
}

#-----------RPCS3-------------
windowrule {
    name = rpcs3-game-window

    match:class = ^(rpcs3)$
    match:title = ^FPS:.*

    float = true
    center = true
    size = (monitor_w*0.67) (monitor_h*0.67)
}

#-----------CHEATSHEET------------
windowrule {
    name = cheatsheet

    match:title = ^(Hyprland Cheat Sheet)$

    float = true
    center = true

    size = 1400 850
}
